name: CI

on:
  push:
    branches:
      - main
      - dev
      - qaenv

jobs:
  run:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10" ]

    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Python Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py')
