name: JMeter Tests

on:
  push:
    branches:
      - qaenv

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run FastAPI Application
        run: |
          cd app/
          nohup python main.py & # Levanta la aplicación en segundo plano
          sleep 5  # Espera un momento para asegurarte de que la aplicación esté completamente levantada

      - name: Install JMeter
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter Tests
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -n -t stress-test.jmx -l result.jtl

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl

